name: 'GitHub PR diff Checker'
description: 'Checks PR diff for word occurrences'
inputs:
  github-token:
    description: 'Github token, added magically'
    required: true
  diffDoesNotContain:
    description: 'Array String that must not be in the PR diff'
    required: true

runs:
  using: 'node12'
  main: 'lib/main.js'